post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjY1YTE2YTg0Y2Y4MWRjOTllYWM3MzYwZiIsImlhdCI6MTcwNTA3NzczMH0.ZcAbLLrbXsLGD01NjQI-eIWc_PkP9R6EOv6l3X2pPjI

{
  "id": "5a422a851b54a676234d17f2",
    "title": "Canonical string reduction",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
    "likes": 21
} 