delete http://localhost:3003/api/blogs/65a16adf83f316fe37141f6a
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjY1YTE2YTg0Y2Y4MWRjOTllYWM3MzYwZiIsImlhdCI6MTcwNTA3NzQ1MH0.tfqdBPBQaWUMXstVDL0X_stY6Kxv2jbE_djbQEaE1PI

 