put http://localhost:3003/api/blogs/5a422b3a1b54a676234d17f9
Content-Type: application/json

{
    "title": "Canonical string reduction",
    "author": "Edger W. Dikjstra",
    "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
    "likes": 12
}